### ISSUE TITLE
[BUG] ES doesn't appear to run on store.steampowered.com

### ISSUE THREAD

**Issue by bowlby4** [jshackles/Enhanced_Steam#1430]
When I am logged out of the Steam store Enhanced Steam runs. Log back in and it doesn't. Runs with no issues on steamcommunity.com.

Here is the console errors
```
Uncaught DOMException: Failed to execute 'setItem' on 'Storage': Setting the value of 'ea_appids' exceeded the quota.
    at setValue (chrome-extension://okadibdjfemgnhjiembecghcbfknbfhg/enhancedsteam.js:221:15)
    at Object.<anonymous> (chrome-extension://okadibdjfemgnhjiembecghcbfknbfhg/enhancedsteam.js:5922:4)
    at i (chrome-extension://okadibdjfemgnhjiembecghcbfknbfhg/js/jQuery.min.js:2:27449)
    at Object.fireWith [as resolveWith] (chrome-extension://okadibdjfemgnhjiembecghcbfknbfhg/js/jQuery.min.js:2:28213)
    at y (chrome-extension://okadibdjfemgnhjiembecghcbfknbfhg/js/jQuery.min.js:4:22721)
    at XMLHttpRequest.c (chrome-extension://okadibdjfemgnhjiembecghcbfknbfhg/js/jQuery.min.js:4:26925)
chrome-extension://okadibdjfemgnhjiembecghcbfknbfhg/enhancedsteam.js:221 Uncaught DOMException: Failed to execute 'setItem' on 'Storage': Setting the value of 'user_login' exceeded the quota.
    at setValue (chrome-extension://okadibdjfemgnhjiembecghcbfknbfhg/enhancedsteam.js:221:15)
    at Object.get_http.xhrFields.withCredentials (chrome-extension://okadibdjfemgnhjiembecghcbfknbfhg/enhancedsteam.js:142:6)
    at i (chrome-extension://okadibdjfemgnhjiembecghcbfknbfhg/js/jQuery.min.js:2:27449)
    at Object.fireWith [as resolveWith] (chrome-extension://okadibdjfemgnhjiembecghcbfknbfhg/js/jQuery.min.js:2:28213)
    at y (chrome-extension://okadibdjfemgnhjiembecghcbfknbfhg/js/jQuery.min.js:4:22721)
    at XMLHttpRequest.c (chrome-extension://okadibdjfemgnhjiembecghcbfknbfhg/js/jQuery.min.js:4:26925)``
```

**Comment by JoiNNN** [comment]
Try clearing ES's cache.

**Comment by bowlby4** [comment]
I should have mentioned it in the original post. I did clear the ES cache, browser cache and made sure there were no extension/script conflicts. I then removed ES and then reinstalled it. No luck.

**Comment by JoiNNN** [comment]
Do you own many games? If so try disabling "Show apps purchase date on store pages" in **Options > Store > General**

**Comment by bowlby4** [comment]
I have over 3000 games. Just disabled it and cleared ES cache. Still doesn't work.

**Comment by JoiNNN** [comment]
Are you getting the same error?

**Comment by bowlby4** [comment]
Yes. The same errors in Chrome console.

**Comment by bowlby4** [comment]
Others said that deleting cookies for store.steampowered.com fixed it for them. I had already deleted them through Chrome, and it didn't fix the issue. I deleted them again and found for some reason they weren't being deleted. Used a program to delete the cookies on boot, and it worked and fixed the issue I was having.

Thanks for all your help.
