### ISSUE TITLE
Glitch

### ISSUE THREAD

**Issue by avi12** [jshackles/Enhanced_Steam#1520]
By the time of writing this issue post, there's a Steam Winter Sale going on.
When I scrolled down a bit, in the section where there are tabs of [Popular New Releases] [Top Sellers] [Upcoming] [Popular] , the tiles grid is being replaced with a rows list, where each row has a game in it.
I'm unsure if it's because of the sale, but as of now there's a glitch, followed by an error with a console output:

> Error in response to storage.get: TypeError: Cannot read property 'data' of undefined
>     at n.fn.init.$.fn.firstText (chrome-extension://okadibdjfemgnhjiembecghcbfknbfhg/enhancedsteam.js:246:78)
>     at Object.callback (chrome-extension://okadibdjfemgnhjiembecghcbfknbfhg/enhancedsteam.js:6791:148)
>     at customize_home_page (chrome-extension://okadibdjfemgnhjiembecghcbfknbfhg/enhancedsteam.js:6748:10)
>     at Array.<anonymous> (chrome-extension://okadibdjfemgnhjiembecghcbfknbfhg/enhancedsteam.js:9156:8)
>     at i (chrome-extension://okadibdjfemgnhjiembecghcbfknbfhg/js/jQuery.min.js:2:27449)
>     at Object.add [as done] (chrome-extension://okadibdjfemgnhjiembecghcbfknbfhg/js/jQuery.min.js:2:27748)
>     at HTMLDocument.<anonymous> (chrome-extension://okadibdjfemgnhjiembecghcbfknbfhg/enhancedsteam.js:9010:68)
>     at i (chrome-extension://okadibdjfemgnhjiembecghcbfknbfhg/js/jQuery.min.js:2:27449)
>     at Object.fireWith [as resolveWith] (chrome-extension://okadibdjfemgnhjiembecghcbfknbfhg/js/jQuery.min.js:2:28213)

Visually, it looks like a mess:
![](https://i.imgur.com/3ywHt53.png)

**Comment by KarlCastle** [comment]
The error in the console is because there's no block of curator recommendations and that's not handled well. It shouldn't be impacting the grid.

The "Popular" tab is a feature added by Enhanced Steam and I think it's relying on some CSS that's not in the Steam style sheet at the moment because of the sale grids. As a result, the text that should be shown next to each icon is pushed down a row and the owned/wishlisted backgrounds are being rendered over the top.

**Comment by VanityFox** [comment]
So, Enhanced Steam is discontinued. There is now [Augmented Steam](https://github.com/tfedor/AugmentedSteam/). Perhaps your requested feature/bugfix is already implemented there! If not, you could move your issue there.
